/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DraftResponseImport } from './routes/draft-response'
import { Route as CommandsImport } from './routes/commands'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as LoginPopupImport } from './routes/login_.popup'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DraftResponseRoute = DraftResponseImport.update({
  id: '/draft-response',
  path: '/draft-response',
  getParentRoute: () => rootRoute,
} as any)

const CommandsRoute = CommandsImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginPopupRoute = LoginPopupImport.update({
  id: '/login_/popup',
  path: '/login/popup',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsImport
      parentRoute: typeof rootRoute
    }
    '/draft-response': {
      id: '/draft-response'
      path: '/draft-response'
      fullPath: '/draft-response'
      preLoaderRoute: typeof DraftResponseImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login_/popup': {
      id: '/login_/popup'
      path: '/login/popup'
      fullPath: '/login/popup'
      preLoaderRoute: typeof LoginPopupImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commands': typeof CommandsRoute
  '/draft-response': typeof DraftResponseRoute
  '/login': typeof LoginRoute
  '/login/popup': typeof LoginPopupRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commands': typeof CommandsRoute
  '/draft-response': typeof DraftResponseRoute
  '/login': typeof LoginRoute
  '/login/popup': typeof LoginPopupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commands': typeof CommandsRoute
  '/draft-response': typeof DraftResponseRoute
  '/login': typeof LoginRoute
  '/login_/popup': typeof LoginPopupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commands'
    | '/draft-response'
    | '/login'
    | '/login/popup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commands'
    | '/draft-response'
    | '/login'
    | '/login/popup'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commands'
    | '/draft-response'
    | '/login'
    | '/login_/popup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommandsRoute: typeof CommandsRoute
  DraftResponseRoute: typeof DraftResponseRoute
  LoginRoute: typeof LoginRoute
  LoginPopupRoute: typeof LoginPopupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommandsRoute: CommandsRoute,
  DraftResponseRoute: DraftResponseRoute,
  LoginRoute: LoginRoute,
  LoginPopupRoute: LoginPopupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/commands",
        "/draft-response",
        "/login",
        "/login_/popup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/commands": {
      "filePath": "commands.tsx"
    },
    "/draft-response": {
      "filePath": "draft-response.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/login_/popup": {
      "filePath": "login_.popup.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
